name: 'MSSQL Import/Export > Marketplace product DB'

on:
  push:
    paths:
      - platform-tools/scripts/mssql-import-export/**
  workflow_dispatch:
    # inputs:
    #   region:
    #     required: true
    #     default: "aueast"
    #     description: "region"
    #     type: string
    #   environment:
    #     required: true
    #     default: "devtest"
    #     description: "environment"
    #     type: string

# defaults:
#   run:
#     shell: bash
#     working-directory: "platform-tools/scripts/mssql-import-export/"

jobs:
  export_db:
    name: Export Azure SQL DB
    runs-on: ubuntu-latest
    #environment: bigw-platform-${{inputs.region}}-${{ inputs.environment }}-plan  
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3.3.0
      with:
        submodules: true
        fetch-depth: 0

    # - name: Log in with Azure
    #   uses: azure/login@v1
    #   with:
    #     creds: '{"clientId": "${{ secrets.ARM_CLIENT_ID }}", "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}", "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}", "tenantId": "${{ secrets.ARM_TENANT_ID }}"}'
    #     enable-AzPSSession: true

    # - name: Azure PowerShell - Export DB to .bacpac file
    #   id: export_db
    #   uses: azure/powershell@v1
    #   with:
    #     inlineScript: |
    #       .\platform-tools\scripts\mssql-import-export\export-mssql-db.ps1
    #     azPSVersion: "latest"
    #   env:
    #     AZURE_SQL_DB_RESOURCEGROUP_NAME: "bigw-rg-dev-aae-marketplaces"
    #     AZURE_SQL_DB_SERVER_NAME: "bigw-mssql-dev-aae-marketplaces-product-srv"
    #     AZURE_SQL_DB_NAME: "marketplaces-product"
    #     STORAGEACCOUNT_ACCESS_KEY: ${{ secrets.MSSQL_BACKUP_STORAGEACCOUNT_KEY }}
    #     STORAGEACCOUNT_NAME: "pradeepmssqlbackup"
    #     STORAGECONTAINER_NAME: "marketplaces-product-bkps"
    #     KEYVAULT_NAME: "bigw-devops-dev-kv"
    #     SQLADMIN_USERNAME_KV_SECRET_NAME: "BIGW-MSSQL-DEV-AAE-MARKETPLACES-PRODUCT-SRV--ADMINISTRATOR-LOGIN"
    #     SQLADMIN_PASSWORD_KV_SECRET_NAME: "BIGW-MSSQL-DEV-AAE-MARKETPLACES-PRODUCT-SRV--ADMINISTRATOR-LOGIN-PASSWORD"  

    - id: export_db
      shell: pwsh
      run: |
        $bacpacUri = "https://pradeepmssqlbackup.blob.core.windows.net/marketplaces-product-bkps/202302020954.bacpac"
        "BACKPAC_FILE_NAME=$bacpacUri" >> $env:GITHUB_OUTPUT

    outputs:
        bacpac_file_name: ${{ steps.export_db.outputs.BACKPAC_FILE_NAME }}

  import_db:
    name: Import Azure SQL DB
    runs-on: ubuntu-latest
    #environment: bigw-platform-${{inputs.region}}-${{ inputs.environment }}-plan  
    needs: [export_db]
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3.3.0
      with:
        submodules: true
        fetch-depth: 0    

    - name: Get bacpack path
      shell: pwsh
      run: Write-Output "BACPAC path - ${{ needs.export_db.outputs.bacpac_file_name }}"
    
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '{"clientId": "${{ secrets.ARM_CLIENT_ID }}", "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}", "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}", "tenantId": "${{ secrets.ARM_TENANT_ID }}"}'
        enable-AzPSSession: true

    - name: Azure PowerShell - Import DB from .bacpac file
      id: import_db
      uses: azure/powershell@v1
      with:
        inlineScript: |
          .\platform-tools\scripts\mssql-import-export\import-mssql-db.ps1
        azPSVersion: "latest"
      env:
        AZURE_SQL_DB_RESOURCEGROUP_NAME: "bigw-rg-dev-aae-marketplaces"
        AZURE_SQL_DB_SERVER_NAME: "bigw-mssql-dev-aae-marketplaces-product-srv"
        AZURE_SQL_DB_NAME_PREFIX: "marketplaces-product-"
        BACPAC_URI: ${{ needs.export_db.outputs.bacpac_file_name }}
        STORAGEACCOUNT_ACCESS_KEY: ${{ secrets.MSSQL_BACKUP_STORAGEACCOUNT_KEY }}
        AZURE_SQL_DB_MAX_SIZE_BYTES: 34359738368
        AZURE_SQL_DB_EDITION: GeneralPurpose
        AZURE_SQL_DB_SERVICE_OBJECTIVE_NAME: GP_S_Gen5_1
        KEYVAULT_NAME: "bigw-devops-dev-kv"
        SQLADMIN_USERNAME_KV_SECRET_NAME: "BIGW-MSSQL-DEV-AAE-MARKETPLACES-PRODUCT-SRV--ADMINISTRATOR-LOGIN"
        SQLADMIN_PASSWORD_KV_SECRET_NAME: "BIGW-MSSQL-DEV-AAE-MARKETPLACES-PRODUCT-SRV--ADMINISTRATOR-LOGIN-PASSWORD"        
