name: 'Test Publish Reports'

on: [workflow_dispatch]

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'reports/junit-test-report.xml'     
