name: 'Test Publish Reports'

on: [workflow_dispatch]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # - name: Publish Test Report (reports/junit-test-report.xml)
      #   uses: mikepenz/action-junit-report@v4
      #   if: always()
      #   with:
      #     report_paths: 'reports/junit-test-report.xml'  
          
      - name: Publish Test Report (dorny/test-reporter)
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: TESTS      
          path: reports/junit-test-report.xml    
          reporter: java-junit
          fail-on-error: 'false'     

      # - name: Publish Test Report (EnricoMi/publish-unit-test-result-action)
      #   uses: EnricoMi/publish-unit-test-result-action/composite@v2
      #   if: always()
      #   with:
      #     files: reports/junit-test-report.xml 
