name: 'Test Publish Reports'

on: [workflow_dispatch]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # - name: Publish Test Report
      #   uses: mikepenz/action-junit-report@v4
      #   if: success() || failure() # always run even if the previous step fails
      #   with:
      #     report_paths: 'reports/junit-test-report.xml'  
          
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: reports/junit-test-report.xml    # Path to test results
          reporter: jest-junit        # Format of test results    
