name: 'Test ENV Approval Workflow'

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        default: dev
        options:
          - dev
          - test
        description: Environment 
      query:
        type: string
        description: Az CLI query
        required: true
        default: '[].name'
      count:
        type: number
        description: Resource Count
        required: true
        default: 7

jobs:
  deploy_dev:
    name: Deploy DEV
    runs-on: ubuntu-latest
    environment: dev
    if: github.event.inputs.env == 'dev'
    steps:
      - run: echo "ENV - ${{github.event.inputs.env}}"