name: 'Test Workflow'

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: printenv
      - shell: pwsh
        run: |
          $PSVersionTable.PSVersion
          Get-InstalledModule | Format-Table
      - name: Run Azure PowerShell script    
        uses: azure/powershell@v1
        with:
          inlineScript: |
            if (Get-Module -ListAvailable -Name Az) {
              Write-Host "Module exists"
            } 
            else {
                Write-Host "Module does not exist"
            }
          azPSVersion: '3.1.0'    
      - shell: pwsh
        run: |
          if (Get-Module -ListAvailable -Name Az) {
              Write-Host "Module exists"
          } 
          else {
              Write-Host "Module does not exist"
          }
      - shell: bash
        run: |
          echo "CLIENT_ID: ${{ vars.CLIENT_ID }}"
          echo "CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}"
      - shell: bash
        run: |
          myName=John
          echo "MY_NAME=$myName" >> $GITHUB_ENV
      - shell: bash
        run: |
          echo "MY_NAME: $MY_NAME"    
      - id: gen_output
        shell: bash
        run: |
          echo "my_age=200" >> $GITHUB_OUTPUT
    outputs:
      my_age: ${{ steps.gen_output.outputs.my_age }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - shell: bash
        run: |
          echo "my_age: ${{ needs.build.outputs.my_age }}"