name: 'Test Workflow'

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: printenv
      - shell: pwsh
        run: |
          $PSVersionTable.PSVersion
      - shell: bash
        run: |
          echo "CLIENT_ID: ${{ vars.CLIENT_ID }}"
          echo "CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}"
      - shell: bash
        run: |
          echo "::set-env name=MY_NAME::John"
      - shell: bash
        run: |
          echo "MY_NAME: $MY_NAME"    
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - shell: bash
  #       run: |
  #         expr 1 + 1 > output.log