name: 'Test ENV Approval Workflow'

on: []

jobs:
  deploy_dev:
    name: Deploy DEV
    runs-on: ubuntu-latest
    environment: dev 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3.3.0
      with:
        submodules: true
        fetch-depth: 0
    
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '{"clientId": "${{ secrets.ARM_CLIENT_ID }}", "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}", "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}", "tenantId": "${{ secrets.ARM_TENANT_ID }}"}'
        enable-AzPSSession: true

    - id: run_bash
      name: Run Bash Script
      shell: bash
      run: |
        az account show
