name: 'Test Workflow'

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: printenv
      - shell: pwsh
        run: |
          $PSVersionTable.PSVersion
      - shell: bash
        run: |
          echo "${{ env.CLIENT_ID }}"
          echo "${{ secrets.CLIENT_SECRET }}"
  
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - shell: bash
  #       run: |
  #         expr 1 + 1 > output.log