name: 'Test Workflow'

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: printenv
      - run: echo $GITHUB_ENV
      - shell: pwsh
        run: |
          $PSVersionTable.PSVersion
      - shell: bash
        run: |
          echo "CLIENT_ID: ${{ vars.CLIENT_ID }}"
          echo "CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}"
      - shell: bash
        run: |
          myName=John
          echo "MY_NAME=$myName" >> $GITHUB_ENV
      - shell: bash
        run: |
          echo "MY_NAME: $MY_NAME"    
      - id: gen_output
        shell: bash
        run: |
          echo "::set-output name=my_age::100"
    outputs:
      my_age: ${{ steps.gen_output.outputs.my_age }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - shell: bash
        run: |
          echo "my_age: ${{ needs.build.outputs.my_age }}"